language: go
sudo: false
go:
  - 1.10.x
os:
  - osx
  - linux
notifications:
  email:
    recipients:
      - archer.vanderwaal@gmail.com
    on_success: always
    on_failure: always
install:
  - go get github.com/mattn/goveralls
  - go get github.com/Masterminds/glide
  - go get github.com/alecthomas/gometalinter
script:
  - go vet
  - glide install -v
  - gometalinter --install
  - gometalinter --config=.gometalinter.json --vendor ./...
  - goveralls -service=travis-ci
  - make release && make clean